#!/usr/bin/env python3
"""Dump full database (schema + data) as SQL to stdout. Run via: railway run -- python database/dump_backup.py > backup.sql"""

import os
import sys
import psycopg2

DATABASE_URL = os.environ.get('DATABASE_URL')
if not DATABASE_URL:
    print("DATABASE_URL not set", file=sys.stderr)
    sys.exit(1)

conn = psycopg2.connect(DATABASE_URL)
conn.set_session(readonly=True)
cursor = conn.cursor()

print("-- Terrascan database backup")
print(f"-- Generated by dump_backup.py")
print()

# Get all user tables
cursor.execute("""
    SELECT tablename FROM pg_tables
    WHERE schemaname = 'public'
    ORDER BY tablename
""")
tables = [row[0] for row in cursor.fetchall()]

# Dump schema: CREATE TABLE statements
for table in tables:
    # Get column definitions
    cursor.execute("""
        SELECT column_name, data_type, character_maximum_length,
               column_default, is_nullable, udt_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        ORDER BY ordinal_position
    """, (table,))
    columns = cursor.fetchall()

    print(f"-- Table: {table}")
    print(f"CREATE TABLE IF NOT EXISTS {table} (")
    col_defs = []
    for col_name, data_type, max_len, default, nullable, udt_name in columns:
        # Build type string
        if udt_name == 'varchar' and max_len:
            type_str = f"VARCHAR({max_len})"
        elif udt_name == 'numeric':
            type_str = "NUMERIC"
        elif udt_name == 'int4':
            type_str = "INTEGER"
        elif udt_name == 'int8':
            type_str = "BIGINT"
        elif udt_name == 'bool':
            type_str = "BOOLEAN"
        elif udt_name == 'text':
            type_str = "TEXT"
        elif udt_name == 'timestamp':
            type_str = "TIMESTAMP"
        elif udt_name == 'float8':
            type_str = "DOUBLE PRECISION"
        else:
            type_str = data_type.upper()

        parts = [f"    {col_name} {type_str}"]
        if default:
            parts.append(f"DEFAULT {default}")
        if nullable == 'NO':
            parts.append("NOT NULL")
        col_defs.append(" ".join(parts))
    print(",\n".join(col_defs))
    print(");\n")

    # Get indexes
    cursor.execute("""
        SELECT indexname, indexdef FROM pg_indexes
        WHERE tablename = %s AND schemaname = 'public'
    """, (table,))
    for idx_name, idx_def in cursor.fetchall():
        print(f"{idx_def};")
    print()

    # Get constraints
    cursor.execute("""
        SELECT conname, pg_get_constraintdef(oid)
        FROM pg_constraint
        WHERE conrelid = %s::regclass
    """, (table,))
    for con_name, con_def in cursor.fetchall():
        if 'PRIMARY KEY' not in con_def:  # Skip PKs, handled above
            print(f"ALTER TABLE {table} ADD CONSTRAINT {con_name} {con_def};")
    print()

# Dump data
for table in tables:
    cursor.execute(f"SELECT COUNT(*) FROM {table}")
    count = cursor.fetchone()[0]
    print(f"-- Data: {table} ({count} rows)", file=sys.stderr)

    if count == 0:
        continue

    # Get column names
    cursor.execute("""
        SELECT column_name FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        ORDER BY ordinal_position
    """, (table,))
    col_names = [row[0] for row in cursor.fetchall()]
    cols_str = ", ".join(col_names)

    # Stream data in batches using server-side cursor
    cursor2 = conn.cursor(name='dump_cursor')
    cursor2.execute(f"SELECT * FROM {table}")

    batch_num = 0
    while True:
        rows = cursor2.fetchmany(1000)
        if not rows:
            break
        batch_num += 1

        for row in rows:
            values = []
            for val in row:
                if val is None:
                    values.append("NULL")
                elif isinstance(val, bool):
                    values.append("TRUE" if val else "FALSE")
                elif isinstance(val, (int, float)):
                    values.append(str(val))
                else:
                    escaped = str(val).replace("'", "''")
                    values.append(f"'{escaped}'")

            print(f"INSERT INTO {table} ({cols_str}) VALUES ({', '.join(values)});")

    cursor2.close()
    print()

conn.close()
print("-- Backup complete", file=sys.stderr)
